services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    depends_on:
      - db

  employeeapi:
    image: ${DOCKER_REGISTRY-}employeeapi
    build:
      context: .
      dockerfile: EmployeeApi/Dockerfile
    depends_on:
      - db

