<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ComponentContract" Version="1.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.9" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.9" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
	  <PackageReference Include="OxyPlot.Core" Version="2.2.0" />
	  <PackageReference Include="OxyPlot.ImageSharp" Version="2.2.0" />
	  <PackageReference Include="PDFsharp-MigraDoc-GDI" Version="6.2.3" />
  </ItemGroup>

	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="license.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	
	<ItemGroup>
		<Reference Include="PluginsContracts">
			<HintPath>..\finally_dll\PluginsContracts.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>