<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWindowsForms>true</UseWindowsForms>
		<Nullable>enable</Nullable>
		<Title>ComponentContract</Title>
		<Version>1.0.$([System.DateTime]::UtcNow.ToString("HHmm"))</Version>
		<Authors>sheym</Authors>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.9" />
	  <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

	<ItemGroup>
		<Reference Include="PluginsContracts">
			<HintPath>..\finally_dll\PluginsContracts.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>
