<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>1.0.1</Version>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>	  
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ComponentContract" Version="1.0.6" />
    <PackageReference Include="ControlsLibraryNet90" Version="1.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

</Project>
